name: la
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.3 <4.0.0"
  flutter: ">=3.38.4"

dependencies:
  cupertino_icons: 1.0.8
  device_info_plus: 12.3.0
  equatable: 2.0.7
  event_bus: 2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_local_notifications: 19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.2.3
  get_it: 9.2.0
  google_fonts: 6.3.3
  hive: 2.2.3
  injectable: 2.7.1
  internet_connection_checker_plus: 2.9.1
  intl: 0.20.2
  logger: 2.6.2
  lottie: 3.3.2
  shared_preferences: 2.5.3
  smooth_page_indicator: 1.2.1
  supabase_flutter: 2.10.3
  uuid: 4.5.2

dev_dependencies:
  build_runner: 2.10.4
  flutter_gen_runner: 5.12.0
  flutter_launcher_icons: 0.14.4
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  injectable_generator: 2.9.1
  intl_utils: 2.8.12
  lint: 2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/icons/flags/
    - assets/images/
    - assets/illustrations/light/
    - assets/illustrations/dark/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/love_assistant_logo.png"

flutter_gen:
  output: lib/presentation/core/assets
  line_length: 120
  assets:
    outputs:
      class_name: AppAssets

flutter_intl:
  main_locale: is
  enabled: true
  class_name: S
  arb_dir: lib/presentation/core/localization
  output_dir: lib/presentation/core/localization
  # to generate manually: dart run intl_utils:generate
